"""
Supabase schema bootstrap — idempotent.
Run: python setup_db.py

Uses a direct PostgreSQL connection (SUPABASE_DB_URL) instead of the PostgREST
RPC layer, which requires a custom exec_sql function to be pre-installed.
"""
import os
import sys
import psycopg2
from dotenv import load_dotenv

load_dotenv()

STATEMENTS = [
    # topics table
    """
    CREATE TABLE IF NOT EXISTS topics (
        id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        slug        text UNIQUE NOT NULL,
        title       text NOT NULL,
        status      text NOT NULL DEFAULT 'queued',
        tags        text[] DEFAULT '{}',
        created_at  timestamptz DEFAULT now(),
        updated_at  timestamptz DEFAULT now()
    )
    """,
    # blog_posts table
    """
    CREATE TABLE IF NOT EXISTS blog_posts (
        id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        topic_id            uuid REFERENCES topics(id) ON DELETE CASCADE,
        research_json       text,
        mdx_draft           text,
        mdx_final           text,
        meta_title          text,
        meta_description    text,
        published_url       text,
        published_at        timestamptz,
        word_count          int DEFAULT 0,
        rejection_log       jsonb DEFAULT '[]',
        created_at          timestamptz DEFAULT now(),
        updated_at          timestamptz DEFAULT now()
    )
    """,
    # Image columns (idempotent — safe to re-run)
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS hero_image_url text",
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS images jsonb DEFAULT '[]'",
    # Last-error column — surfaces worker crash reason in the dashboard
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS last_error text",
    # JSON-LD structured data (Article + FAQPage) — generated by the schema step,
    # sent to the site in the publish payload for injection into <head>.
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS schema_json jsonb",
    # Social kit (LinkedIn carousel + 5 post types + X threads) — generated by the social step.
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS social_json jsonb",
    # Audit verdict (auditor agent) — fact/SEO/angle/ICP gate run after research.
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS audit_json jsonb",
    # Roadmap columns on topics — let seeded posts carry their angle + target keyword
    # so the research agent executes the strategy instead of researching blind.
    "ALTER TABLE topics ADD COLUMN IF NOT EXISTS brief text",
    "ALTER TABLE topics ADD COLUMN IF NOT EXISTS target_keyword text",
    # Autopilot: the slot at which a finished post auto-publishes (24h veto window).
    # status='scheduled' + scheduled_for in the future = waiting; <= now = due to publish.
    "ALTER TABLE topics ADD COLUMN IF NOT EXISTS scheduled_for timestamptz",
    "CREATE INDEX IF NOT EXISTS topics_status_sched_idx ON topics (status, scheduled_for)",
    # ── Analytics: raw blog view events (one row per view) ────────────────────
    # Written server-side by the dashboard's /api/track endpoint (service key),
    # which the published blog pings. The stats page aggregates this table.
    """
    CREATE TABLE IF NOT EXISTS blog_views (
        id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        slug        text NOT NULL,
        path        text,
        referrer    text,
        country     text,
        ua          text,
        session_id  text,
        viewed_at   timestamptz DEFAULT now()
    )
    """,
    "CREATE INDEX IF NOT EXISTS blog_views_slug_idx ON blog_views (slug)",
    "CREATE INDEX IF NOT EXISTS blog_views_viewed_at_idx ON blog_views (viewed_at)",
    # View data is internal-only: RLS on, no anon policy — the service key (used by
    # /api/track and /api/stats) bypasses RLS; anon clients cannot read raw events.
    "ALTER TABLE blog_views ENABLE ROW LEVEL SECURITY",

    # ── Privacy (DPDP Act / GDPR) ────────────────────────────────────────────
    # `session_id` and `ua` are personal data. The raw session id is no longer
    # stored: /api/track now writes a salted SHA-256 digest, which still supports
    # unique-visitor counting but is not reversible to a device identifier.
    # `ua` is reduced to a coarse client family before it is written.
    #
    # `expires_at` gives every row a hard, queryable retention deadline so
    # "we keep view data for N days" is enforced by the database rather than by
    # a promise in a policy document. purge_expired_views() below does the work.
    "ALTER TABLE blog_views ADD COLUMN IF NOT EXISTS expires_at timestamptz",
    "CREATE INDEX IF NOT EXISTS blog_views_expires_idx ON blog_views (expires_at)",
    """
    CREATE OR REPLACE FUNCTION purge_expired_views() RETURNS integer AS $$
    DECLARE removed integer;
    BEGIN
        DELETE FROM blog_views WHERE expires_at IS NOT NULL AND expires_at <= now();
        GET DIAGNOSTICS removed = ROW_COUNT;
        RETURN removed;
    END $$ LANGUAGE plpgsql
    """,

    # ── Agent telemetry ──────────────────────────────────────────────────────
    # One row per pipeline run. Makes cost measurable (content_engine_features
    # §14 flags every current cost figure as estimated, never instrumented) and
    # makes the swarm watchable.
    """
    CREATE TABLE IF NOT EXISTS agent_runs (
        id                  uuid PRIMARY KEY,
        topic_slug          text,
        topic_id            uuid,
        trigger             text,
        status              text NOT NULL DEFAULT 'running',
        started_at          timestamptz DEFAULT now(),
        finished_at         timestamptz,
        duration_ms         bigint,
        total_input_tokens  bigint DEFAULT 0,
        total_output_tokens bigint DEFAULT 0,
        total_cost_usd      numeric(12,6) DEFAULT 0,
        agent_count         int DEFAULT 0,
        error               text
    )
    """,
    "CREATE INDEX IF NOT EXISTS agent_runs_started_idx ON agent_runs (started_at DESC)",
    "CREATE INDEX IF NOT EXISTS agent_runs_slug_idx ON agent_runs (topic_slug)",
    # One row per thing an agent or gate did, ordered by seq within a run.
    """
    CREATE TABLE IF NOT EXISTS agent_events (
        id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        run_id        uuid REFERENCES agent_runs(id) ON DELETE CASCADE,
        seq           int NOT NULL,
        agent         text,
        kind          text NOT NULL,
        detail        jsonb DEFAULT '{}',
        input_tokens  int DEFAULT 0,
        output_tokens int DEFAULT 0,
        cost_usd      numeric(12,6) DEFAULT 0,
        duration_ms   bigint DEFAULT 0,
        at            timestamptz DEFAULT now()
    )
    """,
    "CREATE INDEX IF NOT EXISTS agent_events_run_seq_idx ON agent_events (run_id, seq)",
    "ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE agent_events ENABLE ROW LEVEL SECURITY",

    # ── RLS lockdown ─────────────────────────────────────────────────────────
    # These tables previously carried `FOR SELECT USING (true)` policies, which
    # let anyone holding the anon key (a key that is public by design) read every
    # row — including unpublished drafts, research digests and audit verdicts.
    # Tolerable for one self-owned blog; a cross-tenant data leak the moment a
    # second client exists. The dashboard reads through server-side API routes
    # using the service key, which bypasses RLS, so nothing legitimate needs the
    # anon path. Dropping the policies leaves RLS enabled with no policy = deny.
    "ALTER TABLE topics ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS anon_read_topics ON topics",
    "DROP POLICY IF EXISTS anon_read_blog_posts ON blog_posts",
]


def _run_statements(db_url: str) -> bool:
    conn = psycopg2.connect(db_url)
    conn.autocommit = True
    cur = conn.cursor()
    total = len(STATEMENTS)
    ok = True

    for i, stmt in enumerate(STATEMENTS, 1):
        clean = stmt.strip()
        if not clean:
            continue
        try:
            cur.execute(clean)
            print(f"  [{i}/{total}] OK")
        except Exception as e:
            err = str(e).lower()
            if "already exists" in err or "duplicate" in err:
                print(f"  [{i}/{total}] SKIP (already exists)")
            else:
                print(f"  [{i}/{total}] ERROR: {e}")
                ok = False

    cur.close()
    conn.close()
    return ok


def _verify(db_url: str) -> None:
    conn = psycopg2.connect(db_url)
    cur = conn.cursor()
    for table in ("topics", "blog_posts"):
        try:
            cur.execute(f"SELECT count(*) FROM {table}")
            cur.fetchone()
            print(f"  [OK] {table}")
        except Exception as e:
            print(f"  [FAIL] {table}: {e}")
    cur.close()
    conn.close()


if __name__ == "__main__":
    db_url = os.environ.get("SUPABASE_DB_URL", "")
    if not db_url:
        print("ERROR: SUPABASE_DB_URL not set in .env")
        sys.exit(1)

    print("Setting up Supabase schema...")
    _run_statements(db_url)

    print("\nVerifying tables...")
    _verify(db_url)
    print("\nDone.")
