"""
Supabase schema bootstrap — idempotent.
Run: python setup_db.py

Uses a direct PostgreSQL connection (SUPABASE_DB_URL) instead of the PostgREST
RPC layer, which requires a custom exec_sql function to be pre-installed.
"""
import os
import sys
import psycopg2
from dotenv import load_dotenv

load_dotenv()

STATEMENTS = [
    # topics table
    """
    CREATE TABLE IF NOT EXISTS topics (
        id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        slug        text UNIQUE NOT NULL,
        title       text NOT NULL,
        status      text NOT NULL DEFAULT 'queued',
        tags        text[] DEFAULT '{}',
        created_at  timestamptz DEFAULT now(),
        updated_at  timestamptz DEFAULT now()
    )
    """,
    # blog_posts table
    """
    CREATE TABLE IF NOT EXISTS blog_posts (
        id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        topic_id            uuid REFERENCES topics(id) ON DELETE CASCADE,
        research_json       text,
        mdx_draft           text,
        mdx_final           text,
        meta_title          text,
        meta_description    text,
        published_url       text,
        published_at        timestamptz,
        word_count          int DEFAULT 0,
        rejection_log       jsonb DEFAULT '[]',
        created_at          timestamptz DEFAULT now(),
        updated_at          timestamptz DEFAULT now()
    )
    """,
    # Image columns (idempotent — safe to re-run)
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS hero_image_url text",
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS images jsonb DEFAULT '[]'",
    # Last-error column — surfaces worker crash reason in the dashboard
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS last_error text",
    # JSON-LD structured data (Article + FAQPage) — generated by the schema step,
    # sent to the site in the publish payload for injection into <head>.
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS schema_json jsonb",
    # Social kit (LinkedIn carousel + 5 post types + X threads) — generated by the social step.
    "ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS social_json jsonb",
    # Roadmap columns on topics — let seeded posts carry their angle + target keyword
    # so the research agent executes the strategy instead of researching blind.
    "ALTER TABLE topics ADD COLUMN IF NOT EXISTS brief text",
    "ALTER TABLE topics ADD COLUMN IF NOT EXISTS target_keyword text",
    # RLS — service key bypasses, anon key reads
    "ALTER TABLE topics ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY",
    """
    DO $$ BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies WHERE tablename='topics' AND policyname='anon_read_topics'
        ) THEN
            CREATE POLICY anon_read_topics ON topics FOR SELECT USING (true);
        END IF;
    END $$
    """,
    """
    DO $$ BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies WHERE tablename='blog_posts' AND policyname='anon_read_blog_posts'
        ) THEN
            CREATE POLICY anon_read_blog_posts ON blog_posts FOR SELECT USING (true);
        END IF;
    END $$
    """,
]


def _run_statements(db_url: str) -> bool:
    conn = psycopg2.connect(db_url)
    conn.autocommit = True
    cur = conn.cursor()
    total = len(STATEMENTS)
    ok = True

    for i, stmt in enumerate(STATEMENTS, 1):
        clean = stmt.strip()
        if not clean:
            continue
        try:
            cur.execute(clean)
            print(f"  [{i}/{total}] OK")
        except Exception as e:
            err = str(e).lower()
            if "already exists" in err or "duplicate" in err:
                print(f"  [{i}/{total}] SKIP (already exists)")
            else:
                print(f"  [{i}/{total}] ERROR: {e}")
                ok = False

    cur.close()
    conn.close()
    return ok


def _verify(db_url: str) -> None:
    conn = psycopg2.connect(db_url)
    cur = conn.cursor()
    for table in ("topics", "blog_posts"):
        try:
            cur.execute(f"SELECT count(*) FROM {table}")
            cur.fetchone()
            print(f"  [OK] {table}")
        except Exception as e:
            print(f"  [FAIL] {table}: {e}")
    cur.close()
    conn.close()


if __name__ == "__main__":
    db_url = os.environ.get("SUPABASE_DB_URL", "")
    if not db_url:
        print("ERROR: SUPABASE_DB_URL not set in .env")
        sys.exit(1)

    print("Setting up Supabase schema...")
    _run_statements(db_url)

    print("\nVerifying tables...")
    _verify(db_url)
    print("\nDone.")
